"""add key columns to bunq sessions

Revision ID: f4ddbe1b2acf
Revises: 002_schema_fixes
Create Date: 2026-05-19 11:46:26.122797+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4ddbe1b2acf'
down_revision: Union[str, None] = '002_schema_fixes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bunq_sessions', sa.Column('private_key_pem', sa.Text(), nullable=True))
    op.add_column('bunq_sessions', sa.Column('server_public_key_pem', sa.Text(), nullable=True))
    op.drop_constraint('uq_bunq_sessions_token', 'bunq_sessions', type_='unique')
    op.drop_constraint('uq_ledger_accounts_bunq_id', 'ledger_accounts', type_='unique')
    op.drop_index('ix_ledger_accounts_bunq_account_id', table_name='ledger_accounts')
    op.create_index(op.f('ix_ledger_accounts_bunq_account_id'), 'ledger_accounts', ['bunq_account_id'], unique=True)
    op.drop_index('uq_ledger_entries_payment_debit', table_name='ledger_entries', postgresql_where="(((entry_type)::text = 'DEBIT'::text) AND (payment_id IS NOT NULL))")
    op.drop_index('ix_outbox_status_next_attempt', table_name='outbox', postgresql_where="((status)::text = 'PENDING'::text)")
    op.drop_constraint('uq_outbox_payment_id', 'outbox', type_='unique')
    op.drop_index('ix_outbox_payment_id', table_name='outbox')
    op.create_index(op.f('ix_outbox_payment_id'), 'outbox', ['payment_id'], unique=True)
    op.drop_index('ix_payments_bunq_payment_id', table_name='payments')
    op.drop_constraint('uq_payments_external_id', 'payments', type_='unique')
    op.drop_index('ix_payments_external_id', table_name='payments')
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_webhook_events_retry_pending', table_name='webhook_events', postgresql_where="((status)::text = 'RETRY_PENDING'::text)")
    op.drop_constraint('uq_webhook_events_event_id', 'webhook_events', type_='unique')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_unique_constraint('uq_webhook_events_event_id', 'webhook_events', ['event_id'])
    op.create_index('ix_webhook_events_retry_pending', 'webhook_events', ['retry_after'], unique=False, postgresql_where="((status)::text = 'RETRY_PENDING'::text)")
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.create_index('ix_payments_external_id', 'payments', ['external_id'], unique=False)
    op.create_unique_constraint('uq_payments_external_id', 'payments', ['external_id'])
    op.create_index('ix_payments_bunq_payment_id', 'payments', ['bunq_payment_id'], unique=False)
    op.drop_index(op.f('ix_outbox_payment_id'), table_name='outbox')
    op.create_index('ix_outbox_payment_id', 'outbox', ['payment_id'], unique=False)
    op.create_unique_constraint('uq_outbox_payment_id', 'outbox', ['payment_id'])
    op.create_index('ix_outbox_status_next_attempt', 'outbox', ['next_attempt_at'], unique=False, postgresql_where="((status)::text = 'PENDING'::text)")
    op.create_index('uq_ledger_entries_payment_debit', 'ledger_entries', ['payment_id'], unique=True, postgresql_where="(((entry_type)::text = 'DEBIT'::text) AND (payment_id IS NOT NULL))")
    op.drop_index(op.f('ix_ledger_accounts_bunq_account_id'), table_name='ledger_accounts')
    op.create_index('ix_ledger_accounts_bunq_account_id', 'ledger_accounts', ['bunq_account_id'], unique=False)
    op.create_unique_constraint('uq_ledger_accounts_bunq_id', 'ledger_accounts', ['bunq_account_id'])
    op.create_unique_constraint('uq_bunq_sessions_token', 'bunq_sessions', ['session_token'])
    op.drop_column('bunq_sessions', 'server_public_key_pem')
    op.drop_column('bunq_sessions', 'private_key_pem')
    # ### end Alembic commands ###
